[package]
name = "aggr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build]
target = "wasm32-unknown-unknown"

[dependencies]
wasm-bindgen = "0.2.84"
arrow = "49.0"
thiserror-no-std = "2.0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
