[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "16.0.0"
arrow = "49.0"
size = "0.4.1"
log = "0.4.20"
simplelog = "0.12.1"
thiserror = "1.0.52"
