[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "16.0.0"
js-sys = "0.3.66"
log = "0.4.20"
simplelog = "0.12.1"